### PR TITLE
Need to include gradethis and learnr in Imports

### LINKED ISSUE #19: Doesn't automatically install learnr and gradethis
I think dependencies need to be in `Imports:` as well as `Remotes:`.

### PR DESCRIPTION
**Pull request by richardreeve**
Closes #19 - @soniamitchell - if you do:
```R
remove.packages(c("learnr", "gradethis", "RPiR"))
devtools::install_github("IBAHCM/RPiR")
library(learnr)

remove.packages(c("learnr", "gradethis", "RPiR"))
devtools::install_github("IBAHCM/RPiR#20")
library(learnr)
```
with and without this fix, does the former error for you, but not the latter? If so, I think this is good to go... please do merge it. Otherwise let me know.

### CODE REVIEW

**Comment by richardreeve** [comment]
Windows seems to install `glue` multiple times for no obvious reason... not sure if it's real?

**Comment by richardreeve** [comment]
Good luck with fixing it... you don't need to update the version number by the way - I haven't merged this yet.

**Comment by soniamitchell** [comment]
Thanks! and good catch with the Imports field. I must have been sleeping.

The {glue} installs are dependencies of dependencies. I'm not sure multiple installs is unusual, but for some reason Windows is unhappy with {glue}. I appear to have gone down a rabbit hole...

**Comment by richardreeve** [comment]
We need to find someone with Windows to check whether it actually works... or maybe we could get rid of learnr as an import, because it's a dependency of gradethis and maybe then there won't be duplicated dependencies?

**Comment by soniamitchell** [comment]
Yea.. I thought about that.. but didn’t like it because {learnr} really is one of our dependencies..

**Comment by soniamitchell** [comment]
Turns out {usethis} also has a dependency on {glue}... and Windows is failing the CI again...

**Comment by soniamitchell** [comment]
Alright.. I've fixed it. We can add {learnr} back in as a dependency. We're using a new template, generated using {usethis}, which basically ignore the warnings. Turns out there are multiple packages that generate this warning, {glue} was just the first. I was using an old template, possibly customised..

**Pull request merged**
