### PR TITLE
Updates for Monday's class

### PR DESCRIPTION
**Pull request by richardreeve**
- [x] Update documentation to include text from moodle
- [x] Add in example report and reference to it in appropriate place
- [x] Add reference material to website
- [x] Add more info on loops
- [x] Add more info on flow control
- [x] Add more info on functions

Other material to follow on in Monday-v2

### CODE REVIEW

**Comment by soniamitchell** [comment]
This is cool! I like the to do list and draft PR. I'll have to do that next time...

**Comment by richardreeve** [comment]
Yes, it's a good approach I think. I haven't been doing it so far in this package because I haven't had so many things to add...

**Review by soniamitchell — COMMENTED** [review]
Looks fab to me! I pushed some minor edits because commenting on the branch felt like madness..

**Comment by soniamitchell** [comment]
FYI, one thing you might not agree with me on. I removed the dates, when things were covered, because I'm not sure the students will care (given you've already referenced the practical / lecture) and it's just another thing to update for next year.

**Comment by richardreeve** [comment]
Great thanks, and no problem with the dates. I figured if they really wanted to they could look at the videos, but tbh I can't imagine them doing it! I'll merge it now.

**Pull request merged**
